# MCC OS Partitioning Configuration

efiSystemPartition:     "/boot/efi"
userSwapChoices:        [none, small, suspend, file]
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "btrfs"
supportedFileSystemTypes:  ["btrfs", "ext4"]

# Btrfs subvolumes layout for Timeshift/Snapper compatibility
btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/log
      subvolume: /@log
